# Generated by Django 2.2.6 on 2020-01-18 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, verbose_name='Level number')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField(null=True, verbose_name='Level duration')),
                ('level_types', models.CharField(choices=[('Standart', 'Standart level'), ('Required', 'Required child level to complete standart level'), ('Timeout', 'Timeout level for waiting in a line'), ('Null', 'Null')], max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='game',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='Game number'),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_input', models.CharField(max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AddField(
            model_name='level',
            name='level_next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='games.Level'),
        ),
        migrations.AddField(
            model_name='level',
            name='level_parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='games.Level'),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Level')),
            ],
        ),
    ]
