# Generated by Django 2.2.6 on 2020-01-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200118_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_types',
            field=models.CharField(choices=[('Standart', 'Standart level'), ('Required', 'Required child level to complete standart level'), ('Timeout', 'Timeout level for waiting in a line'), ('Null', 'Null')], max_length=255),
        ),
    ]
