# Generated by Django 2.2.6 on 2020-01-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200118_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='checkpoint',
            field=models.BinaryField(blank=True, null=True, verbose_name='Checkpoint data'),
        ),
        migrations.AddField(
            model_name='register',
            name='level_complete',
            field=models.BooleanField(null=True, verbose_name='Level completed'),
        ),
        migrations.AddField(
            model_name='register',
            name='match',
            field=models.BooleanField(null=True, verbose_name='Input matchet the code'),
        ),
        migrations.AddField(
            model_name='register',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Timestamp'),
        ),
    ]
