# Generated by Django 2.2.6 on 2020-01-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200118_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='checkpoint_required',
            field=models.BooleanField(default=False, verbose_name='Checkpoint required'),
        ),
    ]
