# Generated by Django 2.2.6 on 2020-01-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_code_checkpoint_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sequence',
            field=models.IntegerField(default=0, unique=True, verbose_name='Game number'),
        ),
        migrations.AlterField(
            model_name='level',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='Level number'),
        ),
    ]
