# Generated by Django 2.2.6 on 2020-01-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200120_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
