# Generated by Django 2.2.6 on 2020-01-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
