# Generated by Django 2.2.6 on 2020-01-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20200122_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level_types',
        ),
        migrations.AddField(
            model_name='level',
            name='level_type',
            field=models.CharField(choices=[('Standart', 'Standart level'), ('Required', 'Required child level to complete standart level'), ('Timeout', 'Timeout level for waiting in a line'), ('Bonus', 'Bonus level')], default='Standart', max_length=255),
            preserve_default=False,
        ),
    ]
