# Generated by Django 2.2.6 on 2020-01-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20200127_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='level_start',
            field=models.BooleanField(null=True, verbose_name='Level started'),
        ),
    ]
