# Generated by Django 2.2.6 on 2020-01-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_register_level_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='mission',
            field=models.TextField(null=True),
        ),
    ]
